apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fastapi-backend:2.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP 
    port: 8000
    nodePort: 30091