apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:2.0.7
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP 
    port: 3000
    nodePort: 30090