apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: webapp # Make sure it's in the correct namespace
spec:
  accessModes:
    - ReadWriteMany # Or the access mode that suits your needs
  resources:
    requests:
      storage: 10Gi # Specify the storage capacity you need
  # If you are using dynamic provisioning (recommended):
  storageClassName: hostpath
